// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_LVguQ3zlF7JZ3RPxTdRE1z-aaj6g4KA',
    appId: '1:840321541069:web:5967ee704a80165a78da84',
    messagingSenderId: '840321541069',
    projectId: 'whatsapp-clone-32f8a',
    authDomain: 'whatsapp-clone-32f8a.firebaseapp.com',
    storageBucket: 'whatsapp-clone-32f8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_WgfF7WFW_N2ljuMFosSP-MlULy6FyeU',
    appId: '1:840321541069:android:96f8f8e9e9c7e1ce78da84',
    messagingSenderId: '840321541069',
    projectId: 'whatsapp-clone-32f8a',
    storageBucket: 'whatsapp-clone-32f8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwlWSITcztsXkGKvm3CIoONoIeXDynTvw',
    appId: '1:840321541069:ios:8152d1f830dce8ce78da84',
    messagingSenderId: '840321541069',
    projectId: 'whatsapp-clone-32f8a',
    storageBucket: 'whatsapp-clone-32f8a.appspot.com',
    iosBundleId: 'com.example.whatsappClone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwlWSITcztsXkGKvm3CIoONoIeXDynTvw',
    appId: '1:840321541069:ios:78b397a163624dbe78da84',
    messagingSenderId: '840321541069',
    projectId: 'whatsapp-clone-32f8a',
    storageBucket: 'whatsapp-clone-32f8a.appspot.com',
    iosBundleId: 'com.example.whatsappClone.RunnerTests',
  );
}
